### ISSUE TITLE
CommonJS version

### ISSUE THREAD

**Issue by fdecampredon** [depot/kysely-planetscale#11]
The fact that kysely-planetscale is published as ESM makes it hard for commonjs projects to use it.
Could you publish an commonjs version ?

**Comment by jacobwgillespie** [comment]
Hey, currently `@planetscale/database` is only published as ESM, which is why this module is as well. Originally we had both a CJS and ESM version here, but the CJS version was broken for that reason. 

I think Planetscale's driver would need to publish CJS before we can here.

**Comment by dextermb** [comment]
@fdecampredon Have you managed to get this working nicely? I'm fighting with ts-node to run migrations but I'm encountering difficulties

**Comment by jacobwgillespie** [comment]
@dextermb I've personally had success with `esbuild-register` (https://github.com/egoist/esbuild-register):

```
node -r esbuild-register path/to/file.ts
```

**Comment by dextermb** [comment]
> @dextermb I've personally had success with `esbuild-register` (https://github.com/egoist/esbuild-register):
> 
> 
> 
> ```
> 
> node -r esbuild-register path/to/file.ts
> 
> ```

Thanks, I'll take a looksie 👀

**Comment by ianmcdaniel** [comment]
`@planetscale/database` v1.9.0 now supports CJS 
https://github.com/planetscale/database-js/pull/128

**Comment by jacobwgillespie** [comment]
Nice! CJS support was just released as v1.4.0: https://github.com/depot/kysely-planetscale/releases/tag/v1.4.0
