### ISSUE TITLE
Sending a migration to planetscale?

### ISSUE THREAD

**Issue by exponent28** [depot/kysely-planetscale#13]
Stupid question - how do I push a migration to planetscale? Have followed the Kyesly docs MigrateToLatest() though unable to get this working with the planetscale dialect.

**Comment by jacobwgillespie** [comment]
Hey! Hopefully you've figured this out, I'm less familiar with using Kysely's migration support, but I believe they would run using the mysql2 dialect. Perhaps this is what you're doing now, or maybe there's a way to use the serverless driver for migrations as well.

**Comment by XahidEx** [comment]
I'm also having trouble with it :)
