### ISSUE TITLE
"Boolean" from prisma becomes "number" on types.ts

### ISSUE THREAD

**Issue by orenaksakal** [depot/kysely-planetscale#19]
I have this schema with Prisma

```
model AuthUser {
  id           String        @id @unique
  auth_session AuthSession[]
  auth_key     AuthKey[]

  email          String
  name           String
  email_verified Boolean @default(false)
  test           Boolean

  @@map("auth_user")
}
```

When I auto generate types `email_verified` becomes a `number`

```
export type AuthUser = {
  id: string;
  email: string;
  name: string;
  email_verified: Generated<number>;
  test: number;
};
```

**Comment by jacobwgillespie** [comment]
Hey! So MySQL does not have a boolean column type, so Prisma is choosing to represent booleans as the column type `tinyint` with a value of either 0 for false or 1 for true.

If you don't use `tinyint` columns in any other way, you might be able to write your own custom `cast` function to translate the 1 or 0 into true or false: https://github.com/depot/kysely-planetscale#custom-cast-function.

That said, this library doesn't generate TypeScript types, so you'd also have to update however you auto generate the types to understand the mapping.

What we do in our app is directly work with the numbers 0 or 1:

```typescript
await db.selectFrom('User').where('isAdmin', '=', 1)

await db.update('User').set({isAdmin: 1}).where('email', '=', '...')
```

**Comment by orenaksakal** [comment]
TY @jacobwgillespie !
