### ISSUE TITLE
Publish ESM version

### ISSUE THREAD

**Issue by Cr3atable** [depot/kysely-planetscale#2]
Hello there. The version of `kysely-planetscale` currently on npm is a CJS-only version, and as a result cannot be used in my ESM-based project. I think you should publish versions for both ESM and CJS.

**Comment by jacobwgillespie** [comment]
Hey, thanks for the issue, I've published v0.2.0 as a dual ESM/CJS package, let me know if that works for you!

**Comment by Cr3atable** [comment]
It works perfectly, thank you for fixing this.
