### ISSUE TITLE
need to use planetscale driver if using mysql docker image for development

### ISSUE THREAD

**Issue by JuaniSilva** [depot/kysely-planetscale#21]
I have a planetscale db instance that I use for production with prisma. Now Im trying to migrate to kysely and I have the doubt if I have to make one connection with the normal mysql driver for development since I use a mysql db image in docker for development.

I tried using the url of my docker image to make the connection with the planetscale driver but It gave me an connection error. So I guess Im doing something wrong or this is simply not possible.

**Comment by jacobwgillespie** [comment]
Hey! 👋 So `kysley-planetscale` is only for PlanetScale's serverless database driver (https://github.com/planetscale/database-js), if you're connecting to a local MySQL database or even to PlanetScale using the MySQL protocol, you can use the regular [MySQL dialect](https://kysely-org.github.io/kysely/classes/MysqlDialect.html). In fact we use the regular MySQL dialect ourselves when connecting from some Node services and use the PlanetScale dialect when connecting from Cloudflare Workers.

**Comment by JuaniSilva** [comment]
Oh. It now makes sense, thanks you so much Jacob!
