### ISSUE TITLE
Inserting with a JSON Column

### ISSUE THREAD

**Issue by sebald** [depot/kysely-planetscale#23]
I have a table with a JSON Column. Something like this:

```js
db
  .schema
  .createTable('my_table')
  .addColumn('my_json', 'json')
  .execute();
```

When inserting values I get the following error (shortened to the relevant part):

```
vttablet: rpc error: code = Unknown desc = Invalid JSON text: "Invalid value." at position 1 in value for column 'my_table.my_json'.
```

When I cast the values to strings (`JSON.stringify`) everything works fine. Problem is with the typings, though. Since `keysley` expects the `my_json` property to be an object.

**Comment by jacobwgillespie** [comment]
Hey! For the types, you could change the definition of what Kysely believes that column should be - we use [kysely-codegen](https://github.com/RobinBlomberg/kysely-codegen) to generate the types, and `json` columns are generated as:

```ts
import type {ColumnType} from 'kysely'

export type Json = ColumnType<JsonValue, string, string>

export type JsonArray = JsonValue[]

export type JsonObject = {
  [K in string]?: JsonValue
}

export type JsonPrimitive = boolean | null | number | string

export type JsonValue = JsonArray | JsonObject | JsonPrimitive

export interface MyTable {
  my_column: Json
}
```

Simplifying for your case, you could just directly use `ColumnType`, the three type arguments are for select type, insert type, and update type, so:

```
column: ColumnType<object, string, string>
```

**Comment by sebald** [comment]
@jacobwgillespie thanks for the quick reply! Will look into the codegen lib.

My current issue is not really the types l. It also might be an issue with `kyseley` itself.

The types are fine. But if I `insertInto` and use an object / JSON for the JSON column, planetscale will return the above error. Only if I stringify the column it will work.

It's my first time using `kyseley` so I am not sure if I have to do something different than just pass the object.

**Comment by jacobwgillespie** [comment]
Ah, yeah, I'm not sure if it's a Kysely thing or a MySQL thing, but when inserting or updating, you need to send the `JSON.stringify()` string value, but when selecting you'll get back an object. That `ColumnType<object, string, string>` can help Kysely to enforce that restriction.

We have that behavior with both the PlanetScale serverless driver and with the `mysql2` client using Kysely in our projects, fwiw.

**Comment by sebald** [comment]
@jacobwgillespie good to know, didn't find anything in their docs 😄

So you are using a different type for inserting and selecting the column?
