### ISSUE TITLE
Error isn't handled

### ISSUE THREAD

**Issue by Rawnly** [depot/kysely-planetscale#3]
https://github.com/depot/kysely-planetscale/blob/c3fd469a991b683ee13dc6e9c299c0d8a7cfed20/src/index.ts#L120-L125

The error inside the `executeQuery` method is not handled. `execute` returns an object described as the following:
```ts
export interface ExecutedQuery {
    headers: string[];
    types: Types;
    rows: Row[];
    size: number;
    statement: string;
    insertId: string | null;
    rowsAffected: number | null;
    error: VitessError | null;
    time: number;
}
```

A simple fix is to add 

```ts
if (results.error) {
    throw results.error;
}
```

**Comment by jacobwgillespie** [comment]
@Rawnly thanks for the quick PR, this has been released in version v0.2.1! 🎉 

One note, `@planetscale/database` now natively throws errors as of 1.3.0 (https://github.com/planetscale/database-js/pull/62), so you may want to upgrade that package as well. That said, with your fix here, it'll work for versions <1.3.0. 👍
