### ISSUE TITLE
Boolean values with kysely mysql default for boolean being tinyint

### ISSUE THREAD

**Issue by nadilas** [depot/kysely-planetscale#7]
Has anyone ran into trouble reading numbers instead of boolean values?

https://github.com/depot/kysely-planetscale/blob/5b92e5635a8327911b4b7c90c3394742992abb62/src/index.ts#L161-L165

I added another the following override to get boolean values out, but this only works knowing there is no other use of `tinyint` within the schema:
```ts
if (field.type === "INT8" && value !== null && value !== undefined)
          return parseInt(value) === 1 ? true : false;
```

The kysley default for boolean in mysql is `tinyint`:

https://github.com/koskimas/kysely/blob/b2b3d2e3afcb6722c4b67c9c419dbf354c60ced6/test/node/src/schema.test.ts#L1854-L1862

**Comment by igalklebanov** [comment]
MySQL has no true boolean type. `BOOL` & `BOOLEAN` are just aliases for `TINYINT`.
Kysely doesn't perform any casting.

**Comment by jacobwgillespie** [comment]
To echo what @igalklebanov said, in MySQL, booleans are represented as a `TINYINT` column with the value of either `1` or `0` for true or false.

If you _know_ that you do not use `TINYINT` for anything other than booleans, you could pass a custom `cast` function to convert their values to boolean (they are returned with the type `INT8`):

```typescript
import {Kysely} from 'kysely'
import {PlanetScaleDialect, inflateDates} from 'kysely-planetscale'

const db = new Kysely<Database>({
  dialect: new PlanetScaleDialect({
    url: process.env.DATABASE_URL,
    cast: (field, value) => {
      if (field.type === "INT8" && value === "1") return true
      if (field.type === "INT8" && value === "0") return false
      return inflateDates(field, value)
    },
  }),
})
```

The `field` object has `table` and `name` properties, so you could also conditionally convert to boolean if you do use `TINYINT` for non-boolean use-cases as well.
