### ISSUE TITLE
What is `Database` type, where to get it?

### ISSUE THREAD

**Issue by nikitavoloboev** [depot/kysely-planetscale#9]
`const db = new Kysely<Database>({`

IDE complains that `Database` is undefined. Is there a missing import in readme?

**Comment by jacobwgillespie** [comment]
Hey, that's from Kysely and is a TypeScript interface defining the shape of your database tables and columns. You can write it by hand, or generate it with `kysely-generate`. There's more info in the Kysely docs:

* https://github.com/koskimas/kysely#minimal-example
* https://github.com/koskimas/kysely#generating-types

**Comment by jokull** [comment]
Can also generate it with [prisma-kysely](https://github.com/valtyr/prisma-kysely) and just use Prisma for schema management.
